version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=147521326537.dkr.ecr.us-east-1.amazonaws.com/awsspringbootrestapi
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo Build started on `date`
      - ./mvnw clean package
      - echo Building the Docker image...
      - DOCKER_BUILDKIT=1 docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json


artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
  base-directory: './target'
reports:
  test-report-group: #Junit reports
    files:
      - 'TEST-uk.co.aqubesolutions.awsspringbootrestapi.AwsspringbootrestapiApplicationTests.xml'
    #discard-paths: false #do not remove file paths from test result files
    base-directory: './target/surfire-reports'
